# -*- coding: utf-8 -*-
"""Data_Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsDFbEHZ_HKweYKWb4R8iVXNfD4dVSJ4
"""

pip install opendatasets

















import opendatasets as od
od.download("https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database")

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset ="/content/pima-indians-diabetes-database/diabetes.csv"
df=pd.read_csv(dataset)

print(df.info())



"""Lists"""

a=[1,2,3,3,3,3,4,5]
b=[6,7,8,9]
print(a.pop(5))
print(a)
del(a)

friends=['Sidra','Bushra','Solkar']
for friend in friends:
  print("Eid Mubarak!",friend,"to you and your family")

friends=['Sidra','Bushra','Solkar']
for i in range(len(friends)):
  friend=friends[i]
  print('Eid Mubarak!',friend)

A=[11,2,3,44,5,6]
B=A
A[1]=22
print(A)
print(B)

A=[11,2,3,[2,2,3,4,5,6,6],44,5,6]
B=A[:]
A[1]=22
A[3][1]=5000

print(A)
print(B)

import copy
A=[11,2,3,[2,2,3,4,5,6,6],44,5,6]
B=copy.deepcopy(A)
B[3][1]=5000
print(A)
print(B)

import copy
A=[11,2,3,[2,2,3,4,5,6,6],44,5,6]
B=copy.copy(A)
B[3][1]=5000
print(A)
print(B)

A='Apple  Banana Cat Fish Goat Dog Elf'
B=list(A.split())
B.sort()
print(B)

a=['Rizvi',12,12,23,34,'College']
ls=[]
li=[]
for i in a:
  if isinstance(i,str):
    ls.append(i)
  if isinstance(i,int):
    li.append(i)
print(ls)
print(li)

a=[1,2,3,4,45]
b=[9,8,76,65,4]
a.extend(b)
print(a)
a.sort()
print(a)

a=[1,2,3,4,5,6]
even=[]
odd=[]
for i in a:
  if i%2==0:
    even.append(i)
  if i%2!=0:
    odd.append(i)
print(even)
print(odd)

tup=(2,3,4,5,3,5,5,1)
for i in tup:
  if tup.count(i)>1 :
    print(i,"is repeated")

tup=(2,3,4,5,3,5,5,1)
l=[]
for i in tup:
  if tup.count(i)>1 and l.count(i)==0:
    l.append(i)
    print(i,"is repeated")

set={1,2,3,45,6}
set.remove(45)
print(set)

set={1,2,3,45,6}
set.add(55)
print(set)

set={1,2,3,45,6}
set.pop()
print(set)

set={1,2,3,45,6}
set.clear()
print(set)

a={1,2,3}
b={2,3,4}
a|b
a.union(b)

a={1,2,3}
b={2,3,4}
a&b
a.intersection(b)

a={1,2,3}
b={2,3,4}
a-b
a.difference(b)

a={1,2,3}
b={2,3,4}
a^b
a.symmetric_difference(b)



